add 64-bit LoongArch support
loongarch64-archive/golang-sys pull request #1
Opened 2021-07-07 03:53 UTC by yetist

测试方法：
```
cd cpu; go test -v
cd unix; go test -v
```

2021-07-07 03:53 UTC, yetist commented
@loongarch64/dev-team 请大家review并测试

2021-07-07 04:12 UTC, xen0n commented
cc @mengzhuo

2021-07-09 10:47 UTC, xen0n requested changes
这边还是 `GOARCH=loongarch64` 时代的代码，一些做事情的方式直接照搬了 MIPS64，另外 Linux port 也在上游立正接受批评，一段时间内估计稳定不下来。不能合并。

2021-07-09 10:47 UTC, xen0n commented on cpu/byteorder.go
> +		"loongarch64",
按照 golang/go#46229 决议，应该是 `loong64`。

2021-07-09 10:47 UTC, xen0n commented on cpu/cpu.go
> +var LOONGARCH64 struct {
别的架构名字全大写是因为他们本来就是全大写的缩略词，Loong 不算，因此要叫 `Loong64`。

```go
// Loong64 contains the supported CPU features of the current loong64 platform.
var Loong64 struct {
    // ...
}
```

2021-07-09 10:47 UTC, xen0n commented on cpu/cpu.go
> +	HasSHA3   bool // SHA3 hardware implementation
1. `cpucfg` 可能会不支持吗？
2. 为啥 `FPU LSX LASX LBT LVZ` 几个字段右边没注释？

2021-07-09 10:47 UTC, xen0n commented on cpu/cpu_linux_loongarch64.go
> +// +build loongarch64
`loong64`

另外 `+build` 两行感觉有点怪，是不是抄的别的文件的类似写法？因为正常 `//go:build` 那一行就表达相同含义了。

2021-07-09 10:47 UTC, xen0n commented on cpu/cpu_linux_loongarch64.go
> +	hwcap_LOONGARCH_SHA3   = 1 << 10
这边还是等 Linux 内核相关部分在上游讨论完了，稳定了之后再提吧，否则又要改。

2021-07-09 10:47 UTC, xen0n commented on unix/asm_linux_loongarch64.s
> +	MOVV	a3+24(FP), R6
这边很明显用的是 MIPS64 的 Go 汇编语法，到时候在 Go 上游一定不会允许。这边肯定要重写一版了。

2021-07-10 13:29 UTC, yetist commented
这个等go那边合并了再改成loong64，本来就没打算近期提交，放这里主要是为了解决社区编译不了go应用的问题。

2021-07-12 03:50 UTC, closed without merging